### ISSUE TITLE
level=error msg="processing rx packet error: invalid FCnt or too many dropped frames" 

### ISSUE THREAD

**Issue by lancezhangsf** [brocaar/loraserver#103]
HI brocaar:
i run the loraserver for some time ,then restart my node ,show the error msg:

12月 01 16:23:39 zhangsf-virtual-machine loraserver[3758]: time="2016-12-01T16:23:39+08:00" level=error msg="processing rx packet error: invalid FCnt or too many dropped frames" data_base64="QIHCxQGADgACHhLfJ/Fx"

**Comment by brocaar** [comment]
It is exactly what is says :-) The `FCnt` value must always increment in order to avoid replay attacks, in your case it went back to `0` because of the reset. For convenience you can turn on *Enable relax frame-counter* in the web-interface. The most secure way is to re-activate your node (OTAA) after a reset.
