### ISSUE TITLE
Implement China 470-510 ISM band

### ISSUE THREAD

**Issue by yzk0281** [brocaar/loraserver#42]
How to add ISM band? eg.470-478?

**Comment by ivajloip** [comment]
You need to add a file [here][1] (get inspiration from the already available options) for your band and modify [this][2] in order to be able to use your new ISM band.

[1]: https://github.com/brocaar/lorawan/tree/master/band
[2]: https://github.com/brocaar/lorawan/blob/master/band/band.go#L180

**Comment by Mehradzie** [comment]
@yzk0281 from your previous comment I am assuming you're located in China. I appologise in advance if I'm wrong. 
> seems to be the problem of ‘https://ajax.googleapis.com’， can not access in China~

Based on that assumption, there is defined band for **China** in the **LoraWAN** standard published by *LoRa Alliance*, for `779-787MHz` **ISM Band**. (LoRaWAN 1.0 Specification. Section 7.3)

You can request your own copy of the specification from [this link](https://www.lora-alliance.org/Contact/Request-Specification-Form). And then as @ivajloip pointed out, you can start by copying one of the existing bands (probably the closest one for your ISM band) and start editing it. If you have any problems doing so, I can give you hand if I can open up some free time. :smiley:

**Comment by yzk0281** [comment]
@ivajloip  thanks for answering~
@Mehradzie band range here in China is 470 - 478
I will appreciate that if you could give a hand with this headache problem

**Comment by brocaar** [comment]
@yzk0281 I'm more than happy to help you out with implementing a China band. Unfortunately I'm unable to test it (which is the reason why it isn't implemented yet), but it would be great if we can work together on this.

**Comment by yzk0281** [comment]
@brocaar  I can test it, I got nodes and gateways currently working on 470 -478 but connecting to loraiot
I'm so glad that you can help me with that~
If you add it to the master, I will test it as soon as possible

**Comment by brocaar** [comment]
I've created branch named `test_cn470_510` with a test implementation of the CN 470-510 ISM band. After compiling, you should be able to run `loraserver` with `--band CN_470_510` Looking forward to your test results!

**Comment by yzk0281** [comment]
thank you ~

**Comment by mkurnadi** [comment]
Hi @brocaar could you provide 433 MHz ISM band as well for rest of the world ?

**Comment by brocaar** [comment]
Yes, no problem. Could you please create a separate github issue for this?
And could you let me know if you're able to help out with testing (I don't
have any hardware for this band to test with).

**Comment by mkurnadi** [comment]
Sure, I already have devices to test at 433 MHz. I just opened a separate github issue for this.

**Comment by brocaar** [comment]
@yzk0281 could you please let me know if the following works for you?

- [ ] data up (node -> loraserver)
- [ ] data down (loraserver -> node)
- [ ] OTAA (over-the-air activation)

I'll merge these changes into `master` as soon as I have the confirmation from you (or somebody else who is able to test this ISM band) and tag a new release :-)

**Comment by panyingyun** [comment]
@yzk0281  could you tell me your  email or qq,  Email: panyingyun(at)gmail.com   QQ:919224283. our team also test 470~510 mode, so we can help each other

**Comment by brocaar** [comment]
@panyingyun @yzk0281 if you want, I can provide pre-compiled binaries to test with for the 470-510 band. Just let me know!

**Comment by panyingyun** [comment]
@brocaar    very thank you, please provide  me 470-510 band pre-conmpiled binaries for test, thanks.

**Comment by brocaar** [comment]
here you go! https://www.dropbox.com/sh/amul3hcxz8l1s3h/AAA_u-D-F0MuuzV73VyeXABwa?dl=0

**Comment by Mehradzie** [comment]
Is there a list of ISM bands defined in different countries ? :)
I am still confused about the ISM band range in China as China in the LoraWAN standard is defined for 779-787MHz ISM Band.

**Comment by brocaar** [comment]
The list in the LoRaWAN specs :-) In China there are two ISM band ranges implemented:

* CN470 - 510
* CN779 - 787

For the latter one, I've created a new issue to track it's progress: https://github.com/brocaar/loraserver/issues/50.

**Comment by brocaar** [comment]
@panyingyun were you able to do some testing with the binaries? Looking forward to the results :-)

**Comment by Mehradzie** [comment]
"7.6  CN 470-510MHz Band" :astonished: 
How on earth I have missed this. It's totally missing from my paper copy version. *Mystery*

my bad.

**Comment by panyingyun** [comment]
@brocaar  CN470 - 510  pre-conmpiled binaries   uplink data and activation-by-personalization (ABP)   test ok.    Now do not know how to test  Downlink data  and OTAA

**Comment by ivajloip** [comment]
One way is to send confirmed data from your end-device. If you receive the confirmation, downlink communication works. More complicated way is through pushing data to some mqtt topic. See [this][1] for more information.

[1]: https://docs.loraserver.io/loraserver/sending-data/

**Comment by brocaar** [comment]
@panyingyun looking forward to your downlink test results. Did you manage to get it working? Would be great if we can add this band to LoRa Server :-)

**Comment by panyingyun** [comment]
@brocaar  You can add this band to LoRa Server now. We test all send or receive data OK(uplink /downlink /OTAA/ABP).

**Comment by brocaar** [comment]
Nice! Thanks for testing :-)On 29 Sep 2016, at 04:04, Michael Pan <notifications@github.com> wrote:@brocaar  You can add this band to LoRa Server now. We test all send or receive data OK(uplink /downlink /OTAA/ABP). —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/brocaar/loraserver","title":"brocaar/loraserver","subtitle":"GitHub repository","main_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>","avatar_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>","action":{"name":"Open in GitHub","url":"<a href="<a href="https://github.com/brocaar/loraserver" class="">https://github.com/brocaar/loraserver</a>" class=""><a href="https://github.com/brocaar/loraserver&lt;/a&gt;" class="">https://github.com/brocaar/loraserver&lt;/a&gt;</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@panyingyun in #42: @brocaar  You can add this band to LoRa Server now. We test all send or receive data OK(uplink /downlink /OTAA/ABP). "}],"action":{"name":"View Issue","url":"<a href="<a href="https://github.com/brocaar/loraserver/issues/42#issuecomment-250351774" class="">https://github.com/brocaar/loraserver/issues/42#issuecomment-250351774</a>" class=""><a href="https://github.com/brocaar/loraserver/issues/42#issuecomment-250351774&lt;/a&gt;" class="">https://github.com/brocaar/loraserver/issues/42#issuecomment-250351774&lt;/a&gt;</a>"}}}

**Comment by brocaar** [comment]
This band will be included in the next release (0.12.2).

**Comment by shouhum** [comment]
470-510 uplink is normal, downlink cannot be used, where do I need to debug
