### ISSUE TITLE
redis flushall and device can not join success

### ISSUE THREAD

**Issue by liangyuanpeng** [brocaar/loraserver#435]
### Is this a bug or a feature request?

i run redis flushall and i just got some error 
``
 device-session does not exist or invalid fcnt or mic
``
how can i do for devices?

devices awlays re-join

### What happened?

device join success and send message success

**Comment by brocaar** [comment]
This question has already been answered on the forum: https://forum.loraserver.io/t/recovering-from-a-redis-flushall/6022.

**Comment by stffabi** [comment]
@brocaar is this really by design that a flush of Redis renders all activations useless? This clearly contradicts to the chirpstack network server documentation here: https://www.chirpstack.io/network-server/install/requirements/#redis-database

> ChirpStack Network Server stores all non-persistent data into a Redis datastore.

This sentence at least for me clearly implies all data stored in the Redis is transient and e.g. don't need to be stored in a backup, because they are all non-persistent.

I think a lot of users won't plan to backup their redis store because of this documentation, so all these users are at risk to loose all activations. If you have widely deployed a lot of sensors out in the world for customers, this could probably result in a little nightmare explaining all customer they have to visit all sites and and reset the sensors to rejoin them.
